AllCops:
  Exclude:
    # Block has too many lines
    - spec/controllers/links_controller_spec.rb
    - spec/requests/links_spec.rb
    # Missing top-level class documentation comment  
    - app/controllers/application_controller.rb
    - app/controllers/concerns/exception_handler.rb
    - app/controllers/concerns/response.rb
    - app/controllers/links_controller.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/models/link.rb
    - app/serializers/link_serializer.rb
    - app/helpers/application_helper.rb
    - app/helpers/links_helper.rb
    - config/application.rb
    - db/migrate/20181011155319_create_links.rb
    # Use nested module/class definitions instead of compact style.
    - test/test_helper.rb
    # Other
    - bin/*
    - node_modules/**/*